[WEBINF-1248] - Provide Ubuntu 18 support for nsqd role
sproutsocial/chef-nsq pull request #4
Opened 2019-01-16 19:55 UTC by balanceiskey

* Provides a kitchen environment to view these changes

-------

## Question

The cookbook mostly converges as-expected and I can see an nsqd service running. How can I test if it's actually working?

2019-01-16 20:02 UTC, stahs commented on recipes/nsqd.rb
> +    template '/etc/systemd/system/nsqd.service' do
This should notify a sysctl daemon reload.

i would suggest add to the template resource

`notifies :run, 'execute[systemctl-daemon-reload]'`

and the execute block would look like
```    execute 'systemctl-daemon-reload' do
      command 'systemctl daemon-reload'
      action :nothing
```
see https://github.com/sproutsocial/infra_chef/blob/master/cookbooks/sprout_java/providers/default.rb#L199

2019-01-16 20:18 UTC, balanceiskey commented on recipes/nsqd.rb
> +      notifies :run, 'execute[systemctl-daemon-reload]'
@stahs is this `notifies`in the correct spot or should it be moved into the `reload_services` conditional below?

2019-01-16 20:27 UTC, stahs reviewed
please see comments on service file template

2019-01-16 20:27 UTC, stahs commented on templates/default/systemd.nsqd.conf.erb
> +
under After add StartLimitIntervalSec=30

2019-01-16 20:27 UTC, stahs commented on templates/default/systemd.nsqd.conf.erb
> +
there's a few more directives i'd put in here:

StandardOutput= file:/path/to/nsq/output
StandardError=file:/path/to/nsq/error
Restart=always or on-failure? (I used on failure in sprout java)
RestartSec=1
StartLimitAction= none
StartLimitBurst=5
TimeoutStopSec=5
WorkingDirectory=/path/to/nsq/home

2019-01-16 21:00 UTC, cswingler requested changes

2019-01-16 21:00 UTC, cswingler commented on Berksfile.lock
> +DEPENDENCIES
This file shouldn't be checked in.

2019-01-16 21:00 UTC, cswingler commented on recipes/nsqd.rb
> +      notifies :run, 'execute[systemctl-daemon-reload]'
This should be safe here.

2019-01-16 21:44 UTC, balanceiskey commented on templates/default/systemd.nsqd.conf.erb
> +
What does the `WorkingDirectory` directive do in this case?

2019-01-17 15:54 UTC, balanceiskey commented on templates/default/systemd.nsqd.conf.erb
> +
@stahs stderr/out stuff should be there but not sure what path to lay WorkingDirectory out to.

2019-01-17 19:06 UTC, cswingler requested changes

2019-01-17 19:06 UTC, cswingler commented on recipes/nsqd.rb
> +    if node.platform_family?('debian') && node['platform_version'].to_f >= 18.04
I'd suggest doing `node.platform?('ubuntu')` here, since you're then matching the version based on its ubuntu version and not its debian version.

2019-01-17 19:06 UTC, cswingler commented on recipes/nsqd.rb
> +  if node.platform_family?('debian') && node['platform_version'].to_f >= 18.04
See comment below about this version check logic.

2019-01-18 15:21 UTC, cswingler submitted a review, later dismissed

2019-01-18 19:50 UTC, stahs reviewed
This looks fine except the log files get created with 770 permissions and are not being written to. Standard out is dumped to syslog.

2019-01-18 21:52 UTC, stahs approved these changes
This looks reasonable to me 👍

2019-01-22 15:54 UTC, merged